GET http://localhost:3000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3NDg4NzI0LCJleHAiOjE3MDc0ODg5NjR9.sdXxElGBTOWSOD8OVA5be1kw8E90TQNBLRx7ewSemDM
###
POST http://localhost:3000/auth/login_admin1
Content-Type: application/json

{
    "user":"udin",
    "password":"u123"
}


###
GET http://localhost:3000/auth/token

###
GET http://localhost:3000/auth/testing

###
GET http://localhost:3000/completion1/



#######################################################
### FLOW 1

### submit data di admin1
POST http://localhost:3000/db/admin1Post
Content-Type: application/json

{
    "well_number":"00003",
    "customer_name":"hana aren",
    "well_group":"",
    "progress":"completed"
}

### admin1 untuk list data
GET http://localhost:3000/db/admin1Read


### completion read data
GET http://localhost:3000/db/completionRead/john-00001



### submit di input page 
POST http://localhost:3000/db/earnInput
Content-Type: application/json

{
    "driller":"dilviefre",
    "assistant":"uangelw",
    "diesel_liters":"133",
    "engine_oil":"111",
    "grease_kg":"91",
    "earn_driller":"121",
    "earn_assistant":"920"
}

###read data information page
GET http://localhost:3000/db/earnInput

### edit di page information
POST http://localhost:3000/db/earnEdit13
Content-Type: application/json

{
    "driller":"jothanwwe",
    "assistant":"silvio alemua",
    "earn_driller":"50",
    "earn_assistant":"20"
}

#######################################################