GET http://localhost:3000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA3NDg4NzI0LCJleHAiOjE3MDc0ODg5NjR9.sdXxElGBTOWSOD8OVA5be1kw8E90TQNBLRx7ewSemDM
###
POST http://localhost:3000/auth/login_admin1
Content-Type: application/json

{
    "user":"udin",
    "password":"u123"
}


###
GET http://localhost:3000/auth/token

###
GET https://9143-2001-448a-2061-bafe-589b-2902-a60c-1a54.ngrok-free.app/db/admin1Read

###
GET http://localhost:3000/auth/testing

###
GET http://localhost:3000/completion1/



#######################################################
### FLOW 1

### submit data di admin1
POST http://localhost:3000/db/admin1Post
Content-Type: application/json

{
    "well_number":"00003",
    "customer_name":"hana aren",
    "well_group":"",
    "progress":"completed"
}

### admin1 untuk list data
GET http://localhost:3000/db/admin1Read

### search data
GET http://localhost:3000/db/searchdatah
# Content-Type: application/json

# {
#     "well_number":"00003"
# }


### completion read data
GET http://localhost:3000/db/completionRead/john-00001



### submit di input page 
POST http://localhost:3000/db/inputCost
Content-Type: application/json

{
    "diesel_liters":"2",
    "engine_oil":"0",
    "grease_kg":"0",
    "bentonite_km":"0",
    "cmc_km":"0",
    "hammers_oil":"0"
}
###
GET http://localhost:3000/db/inputCost

###
POST http://localhost:3000/db/inputCost
Content-Type: application/json

{
    "driller":"dilviefre",
    "assistant":"uangelw",
    "diesel_liters":"133",
    "engine_oil":"111",
    "grease_kg":"91",
    "earn_driller":"121",
    "earn_assistant":"920"
}

###read data information page
GET http://localhost:3000/db/earnInput

### edit di page information
POST http://localhost:3000/db/earnEdit13
Content-Type: application/json

{
    "driller":"jothanwwe",
    "assistant":"silvio alemua",
    "earn_driller":"50",
    "earn_assistant":"20"
}

###
DELETE http://localhost:3000/db/earnDelete15


#######################################################


#######################################################
### FLOW 3

POST http://localhost:3000/db/postDriller
Content-Type: application/json

{
    "driller-user": "00001",
    "driller-user-customer-name-input": "john",
    "driller-user-rotary-number": "3",
    "driller-user-address": "",
    "driller-user-date": "",
    "driller-user-meter-drilled-input": "",
    "driller-user-terain-des-input": "",
    "driller-user-water-tables-input": "",
    "driller-bits-type": "",
    "driller-bits-usage-input": "",
    "tricone-bits-quantity": "",
    "tricone-bits-measurement-input": "",
    "tricone-bits-type-input": "",
    "bits-quantity": "",
    "bits-measurement-input": "",
    "casing": "",
    "various": "",
    "daily-consumption-diesel-liters": "",
    "daily-consumption-engine-oil": "",
    "daily-consumption-grease-kg": "",
    "daily-consumption-engine-hour": "",
    "daily-consumption-bentonite-kg": "",
    "daily-consumption-cmc-kg": "",
    "daily-consumption-Hammer-oil-address": "",
    "hammers": "5 Inches",
    "hammers-engine-oil": "",
    "inventory-diesel-liters": "",
    "inventory-grease-kg": "",
    "inventory-bentonite": "",
    "daily-consumption-engine-liters": "",
    "hammer-oil-liters": "",
    "hydraulic-oil-liters": "",
    "reamer-quantity": "",
    "reamer-measurement": "",
    "inches": ""
}

##################### edit host

POST http://localhost:3000/editHost
Content-Type: application/json

{
    "host":"http://localhost:3000"
}

########### Driller user select driller number ###############
GET http://localhost:3000/db/getDataDriller

###### DOWNLOAD
POST http://localhost:3000/db/download?page=completion1
Content-Type: application/json

{
    "Filters":"20",
    "Driller":"John",
    "Assistans":"dani",
    "Charged":"$20",
    "Diesel_liters":"30",
    "Engine_Oil":"90",
    "Grease_Kg":"90",
    "Earnings":"$200",
    "Total_Cost":"$150",
    "Profit":"$350"

}

###
POST http://localhost:3000/db/adminUpdate?id=10
Content-Type: application/json

{
    "data":"in progress"
}