const form = document.querySelector('.container .container__form-data')
const btn_submit = document.querySelector('.container__btn-submit')
const total_depth = document.querySelector('.container .container__completion .total_depth')
const driller_user = document.querySelector('#driller-user-input')
const customer_name = document.querySelector("#driller-user-customer-name-input")